### ISSUE TITLE
安裝完成無法查看配置，顯示如下文

### ISSUE THREAD

**Issue by uwtom** [Jrohy/multi-v2ray#102]
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/multi-v2ray/loader.py", line 7, in <module>
    from profile import Profile
  File "/usr/local/multi-v2ray/profile.py", line 9, in <module>
    from group import SS, Socks, Vmess,Mtproto, Group, Dyport, Quic
  File "/usr/local/multi-v2ray/group.py", line 6, in <module>
    from utils import color_str, Color
  File "/usr/local/multi-v2ray/utils.py", line 7, in <module>
    from OpenSSL import crypto
ModuleNotFoundError: No module named 'OpenSSL'`

**Comment by Jrohy** [comment]
Pip估计没装成功，装成功后`pip3 install pyopenssl`
