### ISSUE TITLE
vps运行出现错误

### ISSUE THREAD

**Issue by phynex** [Jrohy/multi-v2ray#164]
请输入数字选择功能(按回车键退出): 4

Traceback (most recent call last):
  File "/usr/local/multi-v2ray/loader.py", line 23, in load_profile
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/multi-v2ray/loader.py", line 15, in __init__
    self.load_profile()
  File "/usr/local/multi-v2ray/loader.py", line 27, in load_profile
    self.profile = Profile()
  File "/usr/local/multi-v2ray/profile.py", line 27, in __init__
    self.read_json()
  File "/usr/local/multi-v2ray/profile.py", line 59, in read_json
    my_ip = urllib.request.urlopen('http://api.ipify.org').read()
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

欢迎使用 multi-v2ray 管理程序

1.服务管理           2.用户管理

3.更改配置           4.查看配置

5.全局功能           6.更新V2Ray

7.生成客户端配置文件

请输入数字选择功能(按回车键退出): Killed

**Comment by Jrohy** [comment]
网络连不通 http://api.ipify.org ?
