### ISSUE TITLE
从3.06版保资料升级，打不开了。

### ISSUE THREAD

**Issue by anbell2** [Jrohy/multi-v2ray#172]
3.06英文版菜单没有升级，于是用

保持个人资料更新

source <(curl -sL https://git.io/fNgqx) -k

好像没升级成功，v2ray也打不开了。

以下是日志：

Package unzip-6.0-19.el7.x86_64 already installed and latest version
Package git-1.8.3.1-20.el7.x86_64 already installed and latest version
Package ntp-4.2.6p5-28.el7.centos.x86_64 already installed and latest version
Package ntpdate-4.2.6p5-28.el7.centos.x86_64 already installed and latest version
Package socat-1.7.3.2-2.el7.x86_64 already installed and latest version
Package crontabs-1.11-6.20121102git.el7.noarch already installed and latest version
Package lsof-4.87-6.el7.x86_64 already installed and latest version
Nothing to do
Requirement already up-to-date: v2ray_util in /usr/lib/python3.6/site-packages (3.1.0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   678  100   678    0     0   4127      0 --:--:-- --:--:-- --:--:--  4134
Latest version v4.18.0 is already installed.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib64/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib64/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'lang'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 6, in <module>
    from v2ray_util.main import menu
  File "/usr/lib/python3.6/site-packages/v2ray_util/__init__.py", line 3, in <module>
    from .util_core.utils import i18n_create
  File "/usr/lib/python3.6/site-packages/v2ray_util/util_core/__init__.py", line 3, in <module>
    i18n_create()
  File "/usr/lib/python3.6/site-packages/v2ray_util/util_core/utils.py", line 202, in i18n_create
    lang = Config().get_data('lang')
  File "/usr/lib/python3.6/site-packages/v2ray_util/util_core/config.py", line 25, in get_data
    return self.config.get('data', key)
  File "/usr/lib64/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'lang' in section: 'data'

Redirecting to /bin/systemctl restart  v2ray.service
multi-v2ray update success!
Traceback (most recent call last):
  File "/usr/lib64/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib64/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib64/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'lang'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 6, in <module>
    from v2ray_util.main import menu
  File "/usr/lib/python3.6/site-packages/v2ray_util/__init__.py", line 3, in <module>
    from .util_core.utils import i18n_create
  File "/usr/lib/python3.6/site-packages/v2ray_util/util_core/__init__.py", line 3, in <module>
    i18n_create()
  File "/usr/lib/python3.6/site-packages/v2ray_util/util_core/utils.py", line 202, in i18n_create
    lang = Config().get_data('lang')
  File "/usr/lib/python3.6/site-packages/v2ray_util/util_core/config.py", line 25, in get_data
    return self.config.get('data', key)
  File "/usr/lib64/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'lang' in section: 'data'
please input 'v2ray' command to manage v2ray

[root@host ~]#

**Comment by Jrohy** [comment]
`echo "lang=zh" >> /etc/v2ray_util/util.cfg`
执行下这命令再试下运行v2ray

**Comment by anbell2** [comment]
成功了，谢谢！
