### ISSUE TITLE
禁BT 和查流量出现这个是什么意思  换了几次系统了

### ISSUE THREAD

**Issue by nianjiuren** [Jrohy/multi-v2ray#191]
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 10, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/main.py", line 252, in menu
    global_setting()
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/main.py", line 213, in global_setting
    ban_bt.manage()
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/global_setting/ban_bt.py", line 7, in manage
    loader = Loader()
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/loader.py", line 15, in __init__
    self.load_profile()
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/loader.py", line 27, in load_profile
    self.profile = Profile()
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/profile.py", line 28, in __init__
    self.read_json()
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/profile.py", line 71, in read_json
    group = self.parse_group(json_part, index, local_ip)
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/profile.py", line 114, in parse_group
    if conf_stream["httpSettings"]:
KeyError: 'httpSettings'

**Comment by Jrohy** [comment]
因为配置文件少了httpSettings这一项，全新安装应该是没问题的

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/56776128-164c5980-67fd-11e9-92fe-7199dc48503e.png)
这一项

**Comment by nianjiuren** [comment]
好的，感谢大佬，顺便问下，怎么设置分享链接是显示域名而不是ip呢？

Jrohy <notifications@github.com>于2019年4月26日 周五08:27写道：

**Comment by Jrohy** [comment]
开启tls就行
