### ISSUE TITLE
怎么样把一个group中的clients移动到另外一个group

### ISSUE THREAD

**Issue by caoler** [Jrohy/multi-v2ray#205]
直接编辑config.json 会导致异常

点击查看配置:
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 10, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.4/dist-packages/v2ray_util/main.py", line 250, in menu
    V2ray.info()
  File "/usr/local/lib/python3.4/dist-packages/v2ray_util/util_core/v2ray.py", line 28, in info
    print(Loader().profile)
  File "/usr/local/lib/python3.4/dist-packages/v2ray_util/util_core/loader.py", line 15, in __init__
    self.load_profile()
  File "/usr/local/lib/python3.4/dist-packages/v2ray_util/util_core/loader.py", line 27, in load_profile
    self.profile = Profile()
  File "/usr/local/lib/python3.4/dist-packages/v2ray_util/util_core/profile.py", line 28, in __init__
    self.read_json()
  File "/usr/local/lib/python3.4/dist-packages/v2ray_util/util_core/profile.py", line 40, in read_json
    self.config = json.load(json_file)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 2 column 1 (char 1)

具体配置文件：
{
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    },
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    }
  },
  "api": {
    "services": [
      "StatsService"
    ],
    "tag": "api"
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "stats": {},
  "inbounds": [
    {
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "protocol": "vmess",
      "port": 443,
      "tag": "A",
      "settings": {
        "clients": [
          {
            "alterId": 16,
            "id": "ed036fcf-afb5-4792-9a5f-edd1f689f3a3"
          },
          {
            "email": "909399614@qq.com",
            "alterId": 32,
            "id": "b689edb0-3a8d-11e9-b5d8-00163c5febb5"
          },
          {
            "email": "1422014577@qq.com",
            "alterId": 32,
            "id": "f734eba6-3b2a-11e9-a80b-00163c5febb5"
          }
        ]
      },
      "streamSettings": {
        "kcpSettings": {},
        "network": "ws",
        "wsSettings": {
          "path": "/zfgd9jUx/",
          "headers": {
            "Host": "198.xxx.ml"
          },
          "connectionReuse": true
        },
        "quicSettings": {},
        "httpSettings": {},
        "security": "none",
        "tlsSettings": {},
        "tcpSettings": {}
      }
    },
    {
      "tag": "api",
      "listen": "127.0.0.1",
      "settings": {
        "address": "127.0.0.1"
      },
      "protocol": "dokodemo-door",
      "port": 26888
    },
    {
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "alterId": 16,
            "id": "9909a7d2-5cdc-11e9-99e3-00163c5febb5"
          }
        ]
      },
      "streamSettings": {
        "kcpSettings": {},
        "network": "ws",
        "wsSettings": {
          "path": "/DBxsbLOu/",
          "headers": {
            "Host": "198.xxx.ml"
          },
          "connectionReuse": true
        },
        "quicSettings": {},
        "httpSettings": {},
        "security": "none",
        "tlsSettings": {},
        "tcpSettings": {}
      },
      "port": 80
    }
  ],
  "routing": {
    "rules": [
      {
        "outboundTag": "blocked",
        "ip": [
          "0.0.0.0/8",
          "10.0.0.0/8",
          "100.64.0.0/10",
          "169.254.0.0/16",
          "172.16.0.0/12",
          "192.0.0.0/24",
          "192.0.2.0/24",
          "192.168.0.0/16",
          "198.18.0.0/15",
          "198.51.100.0/24",
          "203.0.113.0/24",
          "::1/128",
          "fc00::/7",
          "fe80::/10"
        ],
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      },
      {
        "outboundTag": "api",
        "inboundTag": [
          "api"
        ],
        "type": "field"
      }
    ]
  },
  "log": {
    "access": "/var/log/v2ray/access.log",
    "loglevel": "info",
    "error": "/var/log/v2ray/error.log"
  }
}

**Comment by Jrohy** [comment]
不建议直接修改

**Comment by caoler** [comment]
@Jrohy  那要怎么移动一下呢

**Comment by Jrohy** [comment]
移动必须同类型协议的

**Comment by Jrohy** [comment]
同一协议才能移动，脚本不支持移动，自己改json来试试

**Comment by caoler** [comment]
原因找到了，是因为修改config.json 的时候我是拉取到本地修改的，导致文件编码出了问题，然后json文件无法解析了。
才报出这样的错误

Traceback (most recent call last):
File "/usr/local/bin/v2ray", line 10, in 
sys.exit(menu())
File "/usr/local/lib/python3.4/dist-packages/v2ray_util/main.py", line 250, in menu
V2ray.info()
File "/usr/local/lib/python3.4/dist-packages/v2ray_util/util_core/v2ray.py", line 28, in info
print(Loader().profile)
File "/usr/local/lib/python3.4/dist-packages/v2ray_util/util_core/loader.py", line 15, in init
self.load_profile()
File "/usr/local/lib/python3.4/dist-packages/v2ray_util/util_core/loader.py", line 27, in load_profile
self.profile = Profile()
File "/usr/local/lib/python3.4/dist-packages/v2ray_util/util_core/profile.py", line 28, in init
self.read_json()
File "/usr/local/lib/python3.4/dist-packages/v2ray_util/util_core/profile.py", line 40, in read_json
self.config = json.load(json_file)
File "/usr/lib/python3.4/json/init.py", line 268, in load
parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
File "/usr/lib/python3.4/json/init.py", line 318, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 2 column 1 (char 1)
