### ISSUE TITLE
发现一个问题，此脚本和宝塔面板中的七牛云插件不兼容，不知道怎么回事

### ISSUE THREAD

**Issue by sddtly** [Jrohy/multi-v2ray#214]
发现一个问题，此脚本和宝塔面板中的七牛云插件不兼容，不知道怎么回事
没执行此脚本前正常，执行完就不行了，卸载后也不行，不知道是哪儿的问题

`抱歉，出错了：
Traceback (most recent call last):
File "class/panelPlugin.py", line 1568, in a
plugin_main = __import__(get.name+'_main');
File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
result = _import(*args, **kwargs)
File "plugin/qiniu/qiniu_main.py", line 14, in 
from qiniu import Auth
File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 96, in __import__
result = _import(*args, **kwargs)
ImportError: No module named qiniu`

**Comment by Jrohy** [comment]
默认的pip原改成python3了，建议都不要用python2了，还有几个月python2就到期不维护了

**Comment by Jrohy** [comment]
意味着还没迁移到Python3的包都尽量避免用

**Comment by sddtly** [comment]
嗯嗯 谢谢你大佬
