### ISSUE TITLE
生成客户端配置文件失败

### ISSUE THREAD

**Issue by Slaier** [Jrohy/multi-v2ray#218]
# 配置
443端口 + ws, 走CDN，带域名伪装

# Traceback 
```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'domain'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 10, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/main.py", line 263, in menu
    client.generate()
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/client.py", line 88, in generate
    cw.transform()
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/client.py", line 63, in transform
    content = self.config_factory.get_data("domain")
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/config.py", line 25, in get_data
    return self.config.get('data', key)
  File "/usr/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'domain' in section: 'data'
```

**Comment by Jrohy** [comment]
确实存在，今天出版本修复，感谢反馈

**Comment by Jrohy** [comment]
@Slaier 3.6.0版本已修复
