### ISSUE TITLE
Debian 10 系统安装后运行出错FileNotFoundError

### ISSUE THREAD

**Issue by zolopp** [Jrohy/multi-v2ray#251]
你好，我用的是Debian 10 64位系统
v2ray 用的是233boy 的一键安装版本
安装后通过 /usr/local/bin/v2ray 命令呼出管理菜单
选新增用户提示如下出错

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/loader.py", line 25, in load_profile
    raise FileNotFoundError
FileNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/main.py", line 240, in menu
    user_manage()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/main.py", line 156, in user_manage
    multiple.new_user()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/v2ray.py", line 19, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/config_modify/multiple.py", line 58, in new_user
    gs = GroupSelector(_('add user'))
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/selector.py", line 82, in __init__
    super(GroupSelector, self).__init__(action)
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/selector.py", line 35, in __init__
    loader = Loader()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/loader.py", line 15, in __init__
    self.load_profile()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/loader.py", line 27, in load_profile
    self.profile = Profile()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/profile.py", line 28, in __init__
    self.read_json()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/profile.py", line 40, in read_json
    self.config = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 31 column 3 (char 482)
安装的版本是4.21.3
求帮助！谢谢

**Comment by Jrohy** [comment]
别的服务生成的json不一定能解析的

**Comment by Jrohy** [comment]
用vultr 的debian10 测了下全新安装没问题

**Comment by zolopp** [comment]
感谢回复，意思是说最好是原生的代码，我再试试

**Comment by zolopp** [comment]
p

> 用vultr 的debian10 测了下全新安装没问题

配置好了，很好用，感谢
