### ISSUE TITLE
ubuntu 18.04 LTS 安装异常

### ISSUE THREAD

**Issue by wanejohnson** [Jrohy/multi-v2ray#254]
Created symlink /etc/systemd/system/multi-user.target.wants/v2ray.service -> /etc/systemd/system/v2ray.service.
V2Ray v4.21.3 is installed.
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 5, in <module>
    from v2ray_util.main import menu
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/__init__.py", line 3, in <module>
    from .util_core.trans import _
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/__init__.py", line 1, in <module>
    from .trans import _
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/trans.py", line 10, in <module>
    lang = Config().get_data('lang')
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/config.py", line 16, in __init__
    self.config.read(self.config_path)
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/etc/v2ray_util/util.cfg', line: 1
'Not Found'
/dev/fd/63: line 1: Not: command not found

multi-v2ray install success!

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 5, in <module>
    from v2ray_util.main import menu
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/__init__.py", line 3, in <module>
    from .util_core.trans import _
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/__init__.py", line 1, in <module>
    from .trans import _
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/trans.py", line 10, in <module>
    lang = Config().get_data('lang')
  File "/usr/local/lib/python3.6/dist-packages/v2ray_util/util_core/config.py", line 16, in __init__
    self.config.read(self.config_path)
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/etc/v2ray_util/util.cfg', line: 1
'Not Found'
please input 'v2ray' command to manage v2ray

**Comment by wanejohnson** [comment]
已解决，使用 no-pip分支， https://github.com/Jrohy/multi-v2ray/tree/no-pip，正常安装！
