### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ijpq** [Jrohy/multi-v2ray#264]
1.新增用户
2.新增端口
3.删除用户
4.删除端口

请选择: 3
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/main.py", line 240, in menu
    user_manage()
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/main.py", line 161, in user_manage
    multiple.del_user()
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/v2ray.py", line 19, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/config_modify/multiple.py", line 136, in del_user
    cs = ClientSelector(_('del user'))
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/selector.py", line 43, in __init__
    self.list_size = self.group_list[-1].node_list[-1].user_number
IndexError: list index out of range

**Comment by Jrohy** [comment]
还剩下多少组和多少个用户呢

**Comment by Jrohy** [comment]
有没有手动修改v2ray json 来删用户呢
