### ISSUE TITLE
ipv6 only无法一键安装

### ISSUE THREAD

**Issue by dpk4g** [Jrohy/multi-v2ray#306]
在vutlr开了两台不同地址ipv6 only的vps均无法安装。安装开始有返回结果，但很快就报错，日志如下：

检测到本机没安装v2ray, 正在自动安装..
Failed to fetch release information. Please check your network or try again.
cp: cannot create regular file '/etc/v2ray/config.json': No such file or directory
new UUID: f8ee67ee-60a7-11ea-8d6c-5600029a5aea
new port: 12573
sed: can't read /etc/v2ray/config.json: No such file or directory
random generate (srtp | wechat-video | utp | dtls | wireguard) fake header, new protocol: mKCP + srtp 

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/main.py", line 222, in menu
    V2ray.check()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/v2ray.py", line 142, in check
    cls.new()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/v2ray.py", line 153, in new
    stream.StreamModifier().random_kcp()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/config_modify/stream.py", line 73, in random_kcp
    self.select(choice)
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/config_modify/stream.py", line 36, in select
    sw = StreamWriter(self.group_tag, self.group_index, self.stream_type[index][0])
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/writer.py", line 75, in __init__
    super(StreamWriter, self).__init__(group_tag, group_index)
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/writer.py", line 46, in __init__
    self.config = self.load(self.path)
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/writer.py", line 53, in load
    with open(path, 'r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/v2ray/config.json'
please input 'v2ray' command to manage v2ray

输入v2ray命令再一次循环这个结果。
试了官方一键安装，直接报网络错误，其他版本一键脚本无反应。
是否因为github没有支持ipv6所以无法在纯ipv6的vps上安装？

**Comment by Jrohy** [comment]
要装最新版只能手动安装v2, github不支持ipv6的

**Comment by Jrohy** [comment]
手动下载最新v2ray包放到服务器里， 然后`bash <(curl -L -s https://install.direct/go.sh) -l v2ray-linux-xx.zip` 这样安装

**Comment by dpk4g** [comment]
按照你的指导的方法成功安装了，多谢指教。
大概看了下油管的速度，vutlr家v6 only的网速的确不给力，貌似也有说是v6优化不好的原因。
还有就是还多网站不支持v6访问也是个问题。

**Comment by shengshengman0** [comment]
> 手动下载最新v2ray包放到服务器里， 然后`bash <(curl -L -s https://install.direct/go.sh) -l v2ray-linux-xx.zip` 这样安装
还有一个方法：
①你网站开启cloudflare CDN,支持v4/v6双栈访问
②v2ray安装包直接放在你网站里面
这样ipv6 only vps就可以直接安装了，也是一个支持纯ipv6的脚本了
不这样的方法，可行不可行

**Comment by longchena** [comment]
v2ray-linux-xx.zip 下载地址从哪里找，辛苦提供下路径吧，谢谢

**Comment by Jrohy** [comment]
去v2fly/v2ray-core仓库release里面下载
