### ISSUE TITLE
通过multi配置好后，通过config.json增加新的标签，选择4查看配置，报错

### ISSUE THREAD

**Issue by matthuo333** [Jrohy/multi-v2ray#325]
增加内置DNS到v2r的config.json，重启后出现如下报错。

[root@65 ~]# v2ray info
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/loader.py", line 23, in load_profile
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 223, in menu
    parse_arg()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 94, in parse_arg
    V2ray.info()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/v2ray.py", line 81, in info
    print(Loader().profile)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/loader.py", line 15, in __init__
    self.load_profile()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/loader.py", line 29, in load_profile
    self.profile = Profile()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/profile.py", line 28, in __init__
    self.read_json()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/profile.py", line 40, in read_json
    self.config = json.load(json_file)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 1 (char 125)

**Comment by Jrohy** [comment]
增加的部分发下

**Comment by Jrohy** [comment]
看报错感觉增加的部分不完整，可能少了个括号之类的

**Comment by matthuo333** [comment]
> 增加的部分发下

就是增加内置DNS及分流处理。具体整个config.json详见 https://paste.ubuntu.com/p/grF6JDmxp3/
其中增加的部分已经标注。

另外，将增加的改回。仍然报错。

如果需要恢复到安装后的版本怎么做？

**Comment by Jrohy** [comment]
去掉注释试试

**Comment by matthuo333** [comment]
> 去掉注释试试，json不加注释

试了，仍然报错

**Comment by Jrohy** [comment]
https://www.freeformatter.com/json-escape.html
你可以试下格式化json, 看下怎么变成正常的json文件，这个报错是py 官方json包解释时出问题

**Comment by matthuo333** [comment]
> https://www.freeformatter.com/json-escape.html
> 你可以试下格式化json, 看下怎么变成正常的json文件，这个报错是py 官方json包解释时出问题

看来py对格式解释问题，增加个// 就报错。

**Comment by Jrohy** [comment]
@matthuo333 是的应该都是不可以加注释的json

**Comment by yhyy135** [comment]
遇到同样的问题，标准格式 json 可以正常运行。
v2ray 允许配置文件注释，但 py 官方 json 包应该是不支持的。

**Comment by JRQL** [comment]
我也遇到了同样的问题，请问各位是怎么解决这个问题的？
