### ISSUE TITLE
打开流量统计时报错

### ISSUE THREAD

**Issue by rhjdvsgsgks** [Jrohy/multi-v2ray#37]
`Traceback (most recent call last):  
  File "/usr/local/multi-v2ray/other_setting/stats_ctr.py", line 4, in <module>  
    import write_json  
  File "/usr/local/multi-v2ray/write_json.py", line 9, in <module>  
    from base_util import tool_box  
  File "/usr/local/multi-v2ray/base_util/tool_box.py", line 6, in <module>  
    from OpenSSL import crypto  
ImportError: No module named 'OpenSSL'`

**Comment by rhjdvsgsgks** [comment]
删除重装Python好了
