### ISSUE TITLE
老哥，digtalocean的centos7.x安装说文件有问题，有的还找不到，怎么办？

### ISSUE THREAD

**Issue by xiaotaiqi** [Jrohy/multi-v2ray#397]
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 222, in menu
    V2ray.check()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/v2ray.py", line 146, in check
    cls.new()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/v2ray.py", line 157, in new
    stream.StreamModifier().random_kcp()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/config_modify/stream.py", line 73, in random_kcp
    self.select(choice)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/config_modify/stream.py", line 36, in select
    sw = StreamWriter(self.group_tag, self.group_index, self.stream_type[index][0])
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/writer.py", line 75, in __init__
    super(StreamWriter, self).__init__(group_tag, group_index)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/writer.py", line 46, in __init__
    self.config = self.load(self.path)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/writer.py", line 53, in load

**Comment by tqangxl** [comment]
安装前需要先运行:
mkdir -p /etc/v2ray/
touch /etc/v2ray/config.json

运行失败了，执行下上面的命令，再装一次就OK了

**Comment by Jrohy** [comment]
已修复安装，更新下脚本

**Comment by xiaotaiqi** [comment]
好的，谢谢老哥了。

Jrohy <notifications@github.com> 于2020年8月15日周六 下午8:21写道：

**Comment by xiaotaiqi** [comment]
好的，谢谢老哥
