### ISSUE TITLE
首次安装错误 cannot create regular file '/etc/v2ray/config.json': No such file or directory

### ISSUE THREAD

**Issue by thinkall** [Jrohy/multi-v2ray#401]
检测到本机没安装v2ray, 正在自动安装..
WARN: This script will be obsolete soon, please switch to the fhs-install-v2ray project in time.
URL: https://github.com/v2fly/fhs-install-v2ray
cp: cannot create regular file '/etc/v2ray/config.json': No such file or directory
new UUID: 20a17ba8-
new port: 39630
sed: can't read /etc/v2ray/config.json: No such file or directory
random generate (srtp | wechat-video | utp | dtls | wireguard) fake header, new protocol: mKCP + utp 
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/main.py", line 222, in menu
    V2ray.check()
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/v2ray.py", line 146, in check
    cls.new()
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/v2ray.py", line 157, in new
    stream.StreamModifier().random_kcp()
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/config_modify/stream.py", line 73, in random_kcp
    self.select(choice)
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/config_modify/stream.py", line 36, in select
    sw = StreamWriter(self.group_tag, self.group_index, self.stream_type[index][0])
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/writer.py", line 75, in __init__
    super(StreamWriter, self).__init__(group_tag, group_index)
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/writer.py", line 46, in __init__
    self.config = self.load(self.path)
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/writer.py", line 53, in load
    with open(path, 'r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/v2ray/config.json'
please input 'v2ray' command to manage v2ray

**Comment by Chenx221** [comment]
mkdir -p /etc/v2ray/
touch /etc/v2ray/config.json

**Comment by Jrohy** [comment]
@Chenx221 @thinkall 手动创建文件夹和文件了，已发布新版修复了安装
