### ISSUE TITLE
大神，你好。请教下这个是什么原因导致的？

### ISSUE THREAD

**Issue by garrettdo** [Jrohy/multi-v2ray#407]
欢迎使用 v2ray-util 管理程序

1.服务管理              2.用户管理

3.更改配置              4.查看配置

5.全局功能              6.更新V2Ray

7.生成客户端配置文件         

请选择: 7
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 251, in menu
    client.generate()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/client.py", line 76, in generate
    cs = ClientSelector(_('generate client json'))
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/selector.py", line 43, in __init__
    self.list_size = self.group_list[-1].node_list[-1].user_number
IndexError: list index out of range

**Comment by Jrohy** [comment]
查看下配置，看看有没有配置
