### ISSUE TITLE
更新成最新的v3.8.0版本后，新建用户出错

### ISSUE THREAD

**Issue by faifai8** [Jrohy/multi-v2ray#421]
新建用户提示如下错误

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/main.py", line 240, in menu
    user_manage()
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/main.py", line 156, in user_manage
    multiple.new_user()
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/util_core/v2ray.py", line 18, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/v2ray_util/config_modify/multiple.py", line 73, in new_user
    if type(group.node_list[0]) in (Vmess, Vless, Trojan): 
NameError: name 'Trojan' is not defined

**Comment by Jrohy** [comment]
381版本已修复，运行`v2ray update.sh `更新下，感谢反馈
