### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by cwv587** [Jrohy/multi-v2ray#454]
测到本机没安装v2ray, 正在自动安装..
Installing V2Ray v4.33.0 on x86_64
Downloading V2Ray: https://github.com/v2fly/v2ray-core/releases/download/v4.33.0/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   644  100   644    0     0   1267      0 --:--:-- --:--:-- --:--:--  1267
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com; 未知的错误
Failed to download! Please check your network or try again.
cp: 无法创建普通文件"/etc/v2ray/config.json": 没有那个文件或目录                                      new UUID: 1fe7b282-4776-11eb-be58-008071428c1a
new port: 64110
sed：无法读取 /etc/v2ray/config.json：没有那个文件或目录
random generate (srtp | wechat-video | utp | dtls | wireguard) fake header, new protocol: utp

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 233, in menu                     V2ray.check()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/v2ray.py", line 147, in check
    cls.new()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/v2ray.py", line 171, in new
    stream.StreamModifier().random_kcp()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/config_modify/stream.py", line 105, in random_kcp
    self.select(kcp_list[choice])
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/config_modify/stream.py", line 40, in select    sw = StreamWriter(self.group_tag, self.group_index, sType)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/writer.py", line 73, in __init__
    super(StreamWriter, self).__init__(group_tag, group_index)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/writer.py", line 44, in __init__
    self.config = self.load(self.path)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/writer.py", line 51, in load
    with open(path, 'r') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/v2ray/config.json'
please input 'v2ray' command to manage v2ray                                                          
[root@ecs-UPxwL ~]#

**Comment by Jrohy** [comment]
vps网络问题吗，下不了github资源

**Comment by Jrohy** [comment]
Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com; 未知的错误
Failed to download! Please check your network or try again
检查下dns
