### ISSUE TITLE
错误~不知道啥原因

### ISSUE THREAD

**Issue by Glanwu** [Jrohy/multi-v2ray#480]
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 255, in menu
    V2ray.info()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/v2ray.py", line 83, in info
    print(Loader().profile)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/profile.py", line 33, in __str__
    result = "{}{}".format(result, group)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/group.py", line 257, in __str__
    '''.format(self=self, color_ip=ColorStr.fuchsia(self.ip), node=node,tfo=tfo,dyp=dyp,tls=tls, port_way=port_way)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/group.py", line 117, in __str__
    '''.format(self=self, password=self.password, email=email, network=self.stream()).strip() + "\n"
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/group.py", line 121, in stream
    if self.network == "ws":
AttributeError: 'Vless' object has no attribute 'network'

**Comment by Jrohy** [comment]
有自己改过json吗

**Comment by Glanwu** [comment]
> 有手动改过json文件吗

没有改过，中间就设置了下vless+Xtls，全程没有手动修改任何文件。现在用能用，就是每次选择选项时都会出现这样的错误。
