### ISSUE TITLE
vless+xtls无法修改email

### ISSUE THREAD

**Issue by jipiyan** [Jrohy/multi-v2ray#487]
[问题]
vless+xtls无法修改email

[如何重现]
```shell
# 新安装软件
source <(curl -sL https://multi.netlify.app/v2ray.sh) --zh

# 开启xray
xray

# 更改配置
3.更改配置
请选择: 3
# 更改传输方式
5.更改传输方式
请选择: 5
# 更改传输方式
18.VLESS_XTLS
请选择新的传输方式：18
# 自己配置
# 什么域名啦，Let's encrypt啦，巴拉巴拉小魔仙

# 配置完成后添加用户
2.用户管理
请选择: 2
# 新增用户
1.新增用户
请选择: 1
# 定义邮箱
生成随机邮箱:xxxxxxxx@icloud.com, 回车直接使用或者输入自定义邮箱: xxx@xxx.xx
# 定义xtls流控
3.xtls-rprx-direct
请输入序号选择xtls流控: 3

# 修改序号2用户的email
# 更改配置
3.更改配置
请选择: 3
# 修改email
1.修改email
请选择: 1
请输入数字来 修改email: 1
当前节点email为: xxx@xxx.xx
生成随机邮箱:zzzzzzzz@126.com, 回车直接使用或者输入自定义邮箱: zzz@zzz.zzz

# 报错
Traceback (most recent call last):
  File "/usr/local/bin/xray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/main.py", line 253, in menu
    profile_alter()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/main.py", line 186, in profile_alter
    base.new_email()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/v2ray.py", line 20, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/config_modify/base.py", line 100, in new_email
    cw.write_email(email)
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/writer.py", line 418, in write_email
    self.part_json["settings"][self.client_str][self.client_index].update({"email": email})
KeyError: 'users'
```

[定位]
根据报错出错是在`v2ray_util/util_core/writer.py`的418行
查询到219行导入的vless模板使用配置是clients，与404行的条件不符
```python
# 404行
self.client_str = "clients" if self.part_json["protocol"] == "vmess" else "users"
```

[临时解决方案]
```python
# 404行
self.client_str = "clients" if self.part_json["protocol"] == "vmess" else "users"
# 改为
if self.part_json["protocol"] == "vmess":
    self.client_str = "clients"
elif self.part_json["protocol"] == "vless":
    self.client_str = "clients"
else:
    self.client_str = "users"
```

[改进]
因为不知道"protocol" == "vless"时self.client_str = "clients"是否会影响其他配置，请作者大大从全局看一下如何修改🙏

**Comment by Jrohy** [comment]
感谢反馈，新版已修复
