### ISSUE TITLE
xray的流量统计弹出的错误代码，看看。

### ISSUE THREAD

**Issue by anbell2** [Jrohy/multi-v2ray#505]
Traceback (most recent call last):
  File "/usr/local/bin/xray", line 11, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.4/dist-packages/v2ray_util/main.py", line 257, in menu
    global_setting()
  File "/usr/local/lib/python3.4/dist-packages/v2ray_util/main.py", line 215, in global_setting
    stats_ctr.manage()
  File "/usr/local/lib/python3.4/dist-packages/v2ray_util/global_setting/stats_ctr.py", line 179, in manage
    sf.get_stats(schoice, True, True)
  File "/usr/local/lib/python3.4/dist-packages/v2ray_util/global_setting/stats_ctr.py", line 37, in get_stats
    self.downlink_value = self.__run_command(stats_real_cmd)
  File "/usr/local/lib/python3.4/dist-packages/v2ray_util/global_setting/stats_ctr.py", line 21, in __run_command
    result = bytes.decode(subprocess.run(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).stdout.strip())
AttributeError: 'module' object has no attribute 'run'

**Comment by Jrohy** [comment]
subprocess.run是python3.5开始才有的，得升级下python版本，或者忽略这错误
