### ISSUE TITLE
生成证书时出错

### ISSUE THREAD

**Issue by B2-y** [Jrohy/multi-v2ray#543]
正在获取SSL证书，请稍等..
stoping v2ray...
v2ray stop success !
/bin/sh: /root/.acme.sh/acme.sh: Permission denied
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/main.py", line 234, in menu
    parse_arg()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/main.py", line 126, in parse_arg
    cdn.modify()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/config_modify/cdn.py", line 84, in modify
    CDNModifier(domain, cdn_choice - 1).open(new_port)
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/v2ray.py", line 20, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/config_modify/cdn.py", line 30, in open
    TLSModifier(group.tag, group.index, self.domain).turn_on(False)
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/v2ray.py", line 20, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/config_modify/tls.py", line 44, in turn_on
    gen_cert(input_domain)
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/utils.py", line 203, in gen_cert
    if int(os.popen("/root/.acme.sh/acme.sh -v|tr -cd '[0-9]'").read()) >= 300:
ValueError: invalid literal for int() with base 10: ''

**Comment by Jrohy** [comment]
手动运行下命令看看有没有返回，返回什么: `/root/.acme.sh/acme.sh -v|tr -cd '[0-9]'`

**Comment by B2-y** [comment]
直接运行好像是没问题的，提示
/root/.acme.sh/acme.sh：Permission denied

**Comment by Jrohy** [comment]
chmod +x /root/.acme.sh/acme.sh后再来运行

**Comment by B2-y** [comment]
> `chmod +x /root/.acme.sh/acme.sh`后再来运行

没有报错，但下一行的开始是
284root@serv:~#

**Comment by Jrohy** [comment]
试试升级下acme.sh再来生成证书, `acme.sh --upgrade`

**Comment by Jrohy** [comment]
不一样的错误了，80端口被占用了，先停了相应服务再来申请

**Comment by B2-y** [comment]
可以了，已经可以cdn了，感谢
