### ISSUE TITLE
[BUG]更改email时出错

### ISSUE THREAD

**Issue by miangou** [Jrohy/multi-v2ray#551]
Tip: 同一Group的节点传输方式,端口配置,TLS等设置相同
请输入数字来 修改email: 2
当前节点email为: 29********@qq.com
生成随机邮箱:6ZpG9INa@sina.com, 回车直接使用或者输入自定义邮箱: 
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/main.py", line 257, in menu
    profile_alter()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/main.py", line 190, in profile_alter
    base.new_email()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/util_core/v2ray.py", line 20, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/config_modify/base.py", line 100, in new_email
    cw.write_email(email)
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/util_core/writer.py", line 441, in write_email
    self.part_json["settings"][self.client_str][self.client_index].update({"email": email})
KeyError: 'users'

**Comment by Jrohy** [comment]
这是为什么协议更改的email

**Comment by Jrohy** [comment]
新版以补充trojan协议的邮件修改
