### ISSUE TITLE
当传输方式为vmess+tls时，切换到vless+xtls会提示错误

### ISSUE THREAD

**Issue by gcphym** [Jrohy/multi-v2ray#575]
错误提示
```
Traceback (most recent call last):
  File "/usr/local/bin/xray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/main.py", line 257, in menu
    profile_alter()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/main.py", line 198, in profile_alter
    stream.modify()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/util_core/v2ray.py", line 20, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/config_modify/stream.py", line 162, in modify
    sm.select(sm.stream_type[choice - 1][0])
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/config_modify/stream.py", line 118, in select
    sw.write(**kw)
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/util_core/writer.py", line 333, in write
    if "streamSettings" in self.part_json and "alpn" in self.part_json["streamSettings"]["tlsSettings"] and self.stream_type not in apln_list:
KeyError: 'tlsSettings'
```
其实也不是多大的问题 在脚本里手动重新配置一下tls就解决了

**Comment by Jrohy** [comment]
确实有问题

**Comment by Jrohy** [comment]
新版已修复

**Comment by gcphym** [comment]
谢谢
