### ISSUE TITLE
 Xray-core的Shadowsocks 服务端支持单端口多用户

### ISSUE THREAD

**Issue by gcphym** [Jrohy/multi-v2ray#578]
使用xray内核 脚本提示 当前选择的组为Shadowsocks协议, ss协议只支持一个用户一个端口, 想多用户请新增端口!
然而 Xray-core的Shadowsocks 服务端支持单端口多用户 
https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-AEAD
请问作者是否考虑加上单端口多用户的功能

**Comment by gcphym** [comment]
按照那里的说明 手动修改配置文件  单端口多用户运行正常 但是无法进行流量统计
```
File "/usr/local/lib/python3.9/dist-packages/v2ray_util/util_core/loader.py", line 23, in load_profile
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/main.py", line 261, in menu
    global_setting()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/main.py", line 219, in global_setting
    stats_ctr.manage()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/global_setting/stats_ctr.py", line 68, in manage
    loader = Loader()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/util_core/loader.py", line 15, in __init__
    self.load_profile()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/util_core/loader.py", line 29, in load_profile
    self.profile = Profile()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/util_core/profile.py", line 28, in __init__
    self.read_json()
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/util_core/profile.py", line 66, in read_json
    group = self.parse_group(json_part, index, local_ip)
  File "/usr/local/lib/python3.9/dist-packages/v2ray_util/util_core/profile.py", line 142, in parse_group
    ss = SS(self.user_number, conf_settings["password"], conf_settings["method"], email)
KeyError: 'password'
```
