### ISSUE TITLE
手动修改/etc/xrayconfig.json后，就开始报错无法使用。

### ISSUE THREAD

**Issue by anbell2** [Jrohy/multi-v2ray#593]
我记得以前是可以手动修改配置文件的，为啥现在不行了？
我偶尔会重装VPS，然后配置文件我都有备份，配置文件我是不改的。

以下是报错的内容，我不会整，麻烦看下，要怎么搞？

Traceback (most recent call last):
  File "/usr/local/bin/xray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/main.py", line 261, in menu
    global_setting()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/main.py", line 219, in global_setting
    stats_ctr.manage()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/global_setting/stats_ctr.py", line 68, in manage
    loader = Loader()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/loader.py", line 15, in __init__
    self.load_profile()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/loader.py", line 29, in load_profile
    self.profile = Profile()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/profile.py", line 28, in __init__
    self.read_json()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/profile.py", line 40, in read_json
    self.config = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 41 column 9 (char 1089)

**Comment by Jrohy** [comment]
最好不要自己改，没有保证过手动改都能运行

**Comment by anbell2** [comment]
可是我确实有自己修改的需求，我一般都是改一下UUID，以前都是改了没问题的，现在改了就报错，能不能解决一下。

**Comment by anbell2** [comment]
因为你的UUID不能自定义，只能随机生成，我不得以才用手动修改。改成重装VPS之前的原来的UUID

**Comment by Jrohy** [comment]
这是官方python json库读不到json文件，检查下json文件内容

**Comment by anbell2** [comment]
以及WS的路径也不能自定义，我要修改成重装VPS之前原来的，总之我每次重装VPS，要和原来的配置搞成一致，你好多都不能自定义，我只能手动修改了。以前都是手动修改的，现在却修改完报错了。

**Comment by anbell2** [comment]
难道是编码问题？我试试编码

**Comment by anbell2** [comment]
服了，随便一动，又报错了。

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/loader.py", line 23, in load_profile
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/main.py", line 261, in menu
    global_setting()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/main.py", line 219, in global_setting
    stats_ctr.manage()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/global_setting/stats_ctr.py", line 68, in manage
    loader = Loader()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/loader.py", line 15, in __init__
    self.load_profile()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/loader.py", line 29, in load_profile
    self.profile = Profile()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/profile.py", line 28, in __init__
    self.read_json()
  File "/usr/local/lib/python3.7/dist-packages/v2ray_util/util_core/profile.py", line 40, in read_json
    self.config = json.load(json_file)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 38 column 11 (char 979)

**Comment by anbell2** [comment]
还有，我有两台VPS，我两台的配置必需保持一致，我才能用负载均衡。不手动修改咋行？

**Comment by anbell2** [comment]
咋整啊，求救，整体格式是没动的，在格式没变的情况下，改了UUID和WS的路径。

**Comment by Jrohy** [comment]
json库加载不成功json项目也没办法，得成功加载到json才能处理的，检查下改的内容

**Comment by anbell2** [comment]
是不是有另外一个json文件做校验，要同时改两个？

**Comment by Jrohy** [comment]
没有的

**Comment by anbell2** [comment]
好想哭……………………

**Comment by anbell2** [comment]
即使是什么也不改，就复制出去，再然复制进来替换，权限也一样，照样报错。服了

**Comment by anbell2** [comment]
我总算找到办法修改config文件不报错的方法了，在宝塔面板里使用在线文件编辑的功能。已测试成功。

**Comment by guation** [comment]
应该是可以改的 估计是编辑器把编码换掉了导致脚本按原来的编码读取不出来配置
