### ISSUE TITLE
添加域名后报错

### ISSUE THREAD

**Issue by bewater9** [Jrohy/multi-v2ray#658]
[v3.11.0]这个版本

Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 258, in menu
    V2ray.info()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/v2ray.py", line 85, in info
    print(Loader().profile)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/profile.py", line 33, in __str__
    result = "{}{}".format(result, group)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/group.py", line 272, in __str__
    if self.node_list[0].flow:
AttributeError: 'Vmess' object has no attribute 'flow'

**Comment by shl980404454** [comment]
我是在配置 '11.走CDN(需要域名)' ，输入完域名时候，开始报错，内容同上。

**Comment by Jrohy** [comment]
新版已修复，更新下
