### ISSUE TITLE
添加reality报错

### ISSUE THREAD

**Issue by 1516265148** [Jrohy/multi-v2ray#659]
请输入客户端访问的域名(serverName): music.apple.com
xray x25519: unknown command
Run 'xray help' for usage.
Traceback (most recent call last):
  File "/usr/local/bin/xray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.8/dist-packages/v2ray_util/main.py", line 254, in menu
    user_manage()
  File "/usr/local/lib/python3.8/dist-packages/v2ray_util/main.py", line 173, in user_manage
    multiple.new_port()
  File "/usr/local/lib/python3.8/dist-packages/v2ray_util/util_core/v2ray.py", line 20, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/v2ray_util/config_modify/multiple.py", line 43, in new_port
    modify(new_group_list[-1], new_stream)
  File "/usr/local/lib/python3.8/dist-packages/v2ray_util/util_core/v2ray.py", line 20, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/v2ray_util/config_modify/stream.py", line 163, in modify
    sm.select(sm.stream_type[choice - 1][0])
  File "/usr/local/lib/python3.8/dist-packages/v2ray_util/config_modify/stream.py", line 119, in select
    sw.write(**kw)
  File "/usr/local/lib/python3.8/dist-packages/v2ray_util/util_core/writer.py", line 273, in write
    reality_settings["privateKey"] = x25519_key()[0]
IndexError: list index out of range

**Comment by Jrohy** [comment]
先运行`xray update 1.8.1`升级到最新版xray，再来操作，不然旧版xray没有`xray x25519`命令来生成公私钥的

**Comment by sagitn** [comment]
好的，感谢大佬
