### ISSUE TITLE
请问下，新增不了用户，提示如下，该怎么办呢？

### ISSUE THREAD

**Issue by gboys90** [Jrohy/multi-v2ray#664]
Traceback (most recent call last):
  File "/usr/local/bin/xray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 254, in menu
    user_manage()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 171, in user_manage
    multiple.new_user()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/v2ray.py", line 20, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/config_modify/multiple.py", line 90, in new_user
    nw.create_new_user(**info)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/writer.py", line 617, in create_new_user
    user["flow"] = kw["flow"]

**Comment by Jrohy** [comment]
原来是什么协议的，是否已经更新到最新版

**Comment by gboys90** [comment]
还有新建或者更改为第25中协议会这样提示，看不懂，请大佬指点下
xray x25519: unknown command
Run 'xray help' for usage.
Traceback (most recent call last):
  File "/usr/local/bin/xray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 254, in menu
    user_manage()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 173, in user_manage
    multiple.new_port()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/v2ray.py", line 20, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/config_modify/multiple.py", line 43, in new_port
    modify(new_group_list[-1], new_stream)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/v2ray.py", line 20, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/config_modify/stream.py", line 163, in modify
    sm.select(sm.stream_type[choice - 1][0])
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/config_modify/stream.py", line 119, in select
    sw.write(**kw)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/writer.py", line 273, in write
    reality_settings["privateKey"] = x25519_key()[0]
IndexError: list index out of range

**Comment by Jrohy** [comment]
先运行`xray update v1.8.3`来安装最新版

**Comment by gboys90** [comment]
> 先运行`xray update v1.8.3`来安装最新版

好的，谢谢，我试试

**Comment by gboys90** [comment]
> > 先运行`xray update v1.8.3`来安装最新版
> 
> 好的，谢谢，我试试

试了一下，还是一样提示，估计是我这的问题吧

**Comment by armorUMP45** [comment]
遇到了同样的问题，报错也一样

**Comment by jimmyzhou666** [comment]
@Jrohy VLESS好像都不能新增用户，都有报错。TLS开启后面flow空的原因吗？
IP: xxxxxxxxxxx
Port: 443
TLS: 开启 flow:
ID: xxxxxxxxxxxxxxxxxxxxxxx
Encryption: none
Network: WebSocket host: , path: /3Wxxxxxxxxm/
报错：
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 8, in <module>
    sys.exit(menu())
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 254, in menu
    user_manage()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/main.py", line 171, in user_manage
    multiple.new_user()
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/v2ray.py", line 20, in wrapper
    result = func(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/config_modify/multiple.py", line 90, in new_user
    nw.create_new_user(**info)
  File "/usr/local/lib/python3.6/site-packages/v2ray_util/util_core/writer.py", line 617, in create_new_user
    user["flow"] = kw["flow"]
KeyError: 'flow'
