### ISSUE TITLE
开启tls报错

### ISSUE THREAD

**Issue by Nooooobycat** [Jrohy/multi-v2ray#69]
SPDd9E5yMTsjkvAXKnyp2HGqypuQz0xGJLlNmBJWPAgReGHG8l8Hn7Nz2IilRw+S
9nHA4EQQutePKiHokgItQoHAGmvaw43HE2QSG1b9CJ4AbdzmtHPE+KsYYrUK7Qt9
Edj63s1uAWoM+jS8D1a9nPQioqH5wuA=
-----END CERTIFICATE-----
[Tue Nov 27 07:38:23 UTC 2018] Your cert is in   //涉及隐私手动删除
[Tue Nov 27 07:38:23 UTC 2018] Your cert key is in  //涉及隐私手动删除
[Tue Nov 27 07:38:23 UTC 2018] The intermediate CA cert is in  //涉及隐私手动删除
[Tue Nov 27 07:38:23 UTC 2018] And the full chain certs is there:  //涉及隐私手动删除
Traceback (most recent call last):
  File "/usr/local/multi-v2ray/config_modify/tls.py", line 77, in <module>
    tm.turn_on()
  File "/usr/local/multi-v2ray/config_modify/tls.py", line 40, in turn_on
    self.writer.write_tls(True, crt_file=crt_file, key_file=key_file, domain=input_domain)
  File "/usr/local/multi-v2ray/writer.py", line 266, in write_tls
    Config().set_data("domain", domain)
  File "/usr/local/multi-v2ray/config.py", line 30, in set_data
    self.config.write(open(self.config_path),"w")
  File "/usr/lib/python3.4/configparser.py", line 897, in write
    self._sections[section].items(), d)
  File "/usr/lib/python3.4/configparser.py", line 901, in _write_section
    fp.write("[{}]\n".format(section_name))
io.UnsupportedOperation: not writable

**Comment by Jrohy** [comment]
晚上回去测试下

**Comment by Jrohy** [comment]
@Nooooobycat  已修改，`v2ray update.sh` 更新下脚本， 谢谢反馈
