### ISSUE TITLE
各种错误...这是Python的报错吧

### ISSUE THREAD

**Issue by Tsuk1nose** [Jrohy/multi-v2ray#77]
Traceback (most recent call last):
  File "/usr/local/multi-v2ray/config_modify/ss.py", line 50, in <module>
    gs = GroupSelector('修改SS')
  File "/usr/local/multi-v2ray/selector.py", line 72, in __init__
    self.group = self.group_list[0]
IndexError: list index out of range
Redirecting to /bin/systemctl restart v2ray.service
-------------------------------------------
Traceback (most recent call last):
  File "/usr/local/multi-v2ray/client.py", line 79, in <module>
    cs = ClientSelector('生成客户端json')
  File "/usr/local/multi-v2ray/selector.py", line 39, in __init__
    self.list_size = self.group_list[-1].node_list[-1].user_number
IndexError: list index out of range
----------------------------------------------
Traceback (most recent call last):
  File "/usr/local/multi-v2ray/user_manage/create_new_user.py", line 8, in <module>
    gs = GroupSelector('user数量')
  File "/usr/local/multi-v2ray/selector.py", line 72, in __init__
    self.group = self.group_list[0]
IndexError: list index out of range
Redirecting to /bin/systemctl restart v2ray.service

**Comment by Jrohy** [comment]
越界错误，怎么出发的呢

**Comment by Tsuk1nose** [comment]
都是同样的错....

**Comment by Tsuk1nose** [comment]
怎么触发的?我不知道啊,使用的v2ray打开的快捷配置

**Comment by Jrohy** [comment]
能否全新安装看下呢

**Comment by Tsuk1nose** [comment]
嗯?明明都是全新安装但是第二次就没问题了,问题解决,谢谢
