### ISSUE TITLE
查看配置报错

### ISSUE THREAD

**Issue by rhjdvsgsgks** [Jrohy/multi-v2ray#83]
已经看过 #63 和 #74 
.bashrc里有
export PYTHONPATH=$PYTHONPATH:/usr/local/multi-v2ray
这一段

下面是查看配置时报的错
`Traceback (most recent call last):
  File "/usr/local/multi-v2ray/loader.py", line 25, in load_profile
    raise FileNotFoundError
FileNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/multi-v2ray/loader.py", line 15, in __init__
    self.load_profile()
  File "/usr/local/multi-v2ray/loader.py", line 27, in load_profile
    self.profile = Profile()
  File "/usr/local/multi-v2ray/profile.py", line 27, in __init__
    self.read_json()
  File "/usr/local/multi-v2ray/profile.py", line 39, in read_json
    self.config = json.load(json_file)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 38 column 1 (char 769)`

**Comment by Jrohy** [comment]
Json解析有问题，检查下json文件

**Comment by rhjdvsgsgks** [comment]
@Jrohy 用jq检查了下配置，发现是不能有注释的，把注释删掉用jq检查正常了，但会出现

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'Loader'

**Comment by Jrohy** [comment]
什么vps商的什么系统呢

**Comment by Jrohy** [comment]
这是旧配置文件吧，升级下脚本自动转换新版配置文件

**Comment by rhjdvsgsgks** [comment]
@Jrohy 能否强制转换配置文件？前面升级的时候开着v2ray用ssh连上服务器升的，然后升到了一半就断开连接了，再次登进去就已经是新版本了，说已是最新

**Comment by rhjdvsgsgks** [comment]
@Jrohy 我把 inbound 手动替换成了 inbounds ，然后这样报错


Traceback (most recent call last):
  File "/usr/local/multi-v2ray/loader.py", line 25, in load_profile
    raise FileNotFoundError
FileNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/multi-v2ray/loader.py", line 15, in __init__
    self.load_profile()
  File "/usr/local/multi-v2ray/loader.py", line 27, in load_profile
    self.profile = Profile()
  File "/usr/local/multi-v2ray/profile.py", line 27, in __init__
    self.read_json()
  File "/usr/local/multi-v2ray/profile.py", line 43, in read_json
    conf_rules = self.config["routing"]["rules"]
KeyError: 'rules'

可我的 routing 下面有 rules

**Comment by Jrohy** [comment]
不要手动替换，`v2ray update.sh`更新，会自动升级到新版配置文件

**Comment by rhjdvsgsgks** [comment]
@Jrohy 
当前以keep保留配置文件形式更新, 若失败请用全新安装

multi-v2ray当前版本: v2.5.3, 已是最新!!!

**Comment by rhjdvsgsgks** [comment]
搞定了 
`v2ray update.sh 2.5.3`
即可
