### ISSUE TITLE
安装v2ray失败 CentOS7.5 64bit

### ISSUE THREAD

**Issue by Seekerzero** [Jrohy/multi-v2ray#89]
cp: cannot stat ‘/usr/local/multi-v2ray/v2ray’: No such file or directory
chmod: cannot access ‘/usr/local/bin/v2ray’: No such file or directory
bash: /etc/bash_completion.d/v2ray.bash: No such file or directory
cp: cannot stat ‘/usr/local/multi-v2ray/json_template/server.json’: No such file or directory
sed: can't read /etc/v2ray/config.json: No such file or directory
sed: can't read /etc/v2ray/config.json: No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'config_modify'
python3: can't open file '/usr/local/multi-v2ray/client.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>

**Comment by Seekerzero** [comment]
没事了，这个机子没装gitQAQ

**Comment by Jrohy** [comment]
什么vps商的centos7.5呢

**Comment by Seekerzero** [comment]
gigsgigs cloud

**Comment by Seekerzero** [comment]
直接装 v2是可以的
然后试了一下233的脚本也是可以的
不知道是不是哪个源没有装好还是怎样

**Comment by Jrohy** [comment]
可能软件源不行， 连git都不能自动装

**Comment by Jrohy** [comment]
可惜我没gigsgigs cloud 这机器测试

**Comment by Seekerzero** [comment]
最近阿里云比较抽风
换个机器试试，
所以说有什么补救办法吗

**Comment by Jrohy** [comment]
试下debian9系统

**Comment by Seekerzero** [comment]
OK,我过两天试试

**Comment by Seekerzero** [comment]
其实如果源不行的话，debian9有救吗

**Comment by Seekerzero** [comment]
QAQ

**Comment by Jrohy** [comment]
看了下价格，优化不起😂

**Comment by Seekerzero** [comment]
我可以把服务器给你

**Comment by Seekerzero** [comment]
QAQ

**Comment by Seekerzero** [comment]
所以怎么说

**Comment by Jrohy** [comment]
留个telegram， 我私聊你

**Comment by Seekerzero** [comment]
Seeker

**Comment by Seekerzero** [comment]
还是要给电话号码

**Comment by Jrohy** [comment]
尽量别给电话号码

**Comment by Seekerzero** [comment]
那你怎么找得到我
QAQ

**Comment by Seekerzero** [comment]
不太会用telegram

**Comment by Jrohy** [comment]
你有在什么知名群组吗

**Comment by Seekerzero** [comment]
根据地QAQ

**Comment by Seekerzero** [comment]
doubi

**Comment by Jrohy** [comment]
ok我找找
