### ISSUE TITLE
debian7 小鸡安装报错

### ISSUE THREAD

**Issue by wotlitn** [Jrohy/multi-v2ray#93]
V2ray配置信息:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/multi-v2ray/loader.py", line 7, in <module>
    from profile import Profile
  File "/usr/local/multi-v2ray/profile.py", line 9, in <module>
    from group import SS, Socks, Vmess,Mtproto, Group, Dyport, Quic
  File "/usr/local/multi-v2ray/group.py", line 6, in <module>
    from utils import color_str, Color
  File "/usr/local/multi-v2ray/utils.py", line 6, in <module>
    from enum import Enum, unique
ImportError: No module named enum
输入 v2ray 回车即可进行服务管理

**Comment by Jrohy** [comment]
python3有安装成功? enum是python内置模块😂
